### ISSUE TITLE
x2go

### ISSUE THREAD

**Issue by loveshack** [N8-CIR-Bede/documentation#133]
Presumably the x2go service should be documented.

**Comment by ptheywood** [comment]
From an email thread:

> Regarding x2go, it works on Bede as long as you are choosy over what you
run and ask for a session type of "Published applications". Anything MATE
related won't, but an xterm will - which at least is a start.

I've no experience with x2go personsally, would you be able to provide any more information on its usage or what / where in the documentation you would expect this to go (usage maybe?)?

**Comment by bodgerer** [comment]
Jumping in...

x2go wasn't previously documented on Bede because it didn't play nicely with the version of RHEL7/ppc64le we had available. I've just tried it and it seems to be working fine on RHEL8 now, which is nice. You do have to ask for Published Applications rather than a desktop, as Bede isn't really a virtual desktop service!

One change I've made today is install mate-terminal, which is a better terminal emulator than xterm. It either wasn't available or wasn't working under x2go earlier in the year, but seems to be ok now.

For reference, here's the documentation we used for our internal service, which is configured in the same way (although MATE Terminal should be used instead of Xterm):

https://www.dur.ac.uk/arc/hamilton/usage/login/#tab-group-7128

**Comment by bodgerer** [comment]
Looking at how documentation for X2GO could be added. Some users may find more extensive text with pictures useful. 

We could add brief instructions to the "Login" section, and aim to provide a longer "Guide" or "FAQ" entry later on?

**Comment by bodgerer** [comment]
See PR #162

**Comment by bodgerer** [comment]
x2go is now documented
