### ISSUE TITLE
Add jaxlib to the pip or conda channels

### ISSUE THREAD

**Issue by CuongNN218** [N8-CIR-Bede/documentation#209]
Dear Bede team,

I am a phd student using bede server for my research project however, when I tried to install requirement packages for jax a.k.a.
jaxlib using pip in my conda environment, pip could not find it version. Or when I tried to add opence-channel, there is no jaxlib in this channel. How could i resolve my problem when installing jax?

Since jax is quite popular right now, could you support it on the server as Pytorch or Tensorflow?

P/s: I attach screenshots from my terminal for a better understanding current situation. I hope this help
<img width="659" alt="image" src="https://github.com/user-attachments/assets/73e7e385-969a-4ca5-bb92-1438245feebf">
<img width="614" alt="image" src="https://github.com/user-attachments/assets/8703010e-3108-4842-ba47-83e82d42d72f">

**Comment by ptheywood** [comment]
Hi, 

This repository is just for the documentation, rather than software installation requests etc. 

You should contact your local Bede support staff, as listed on the [Bede website](https://n8cir.org.uk/bede/rse-support-bede/), which for Durham is `durham-bede-support@n8cir.org.uk`

---

Unfortunately python packages compilers for ppc64le CPUs are quite limited. 

The OSU `current` channel does include jax/jaxlib 0.4.23 basd on the [file listing](https://ftp.osuosl.org/pub/open-ce/current/), but your requirements seem to be specifying it must come from conda forge, which does not provide ppc64le package. 

You may have more luck with recent packages on the Grace-Hopper nodes, as aarch64 package availability for recent packages tends to be better than for ppc64le. 

Hopefully your local RSE support will be able to help. If so we can add the resolution to the documentation to help others.
